name: Accessibility Scanner
on: workflow_dispatch

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: lindseywild/accessibility-scanner@copilot/add-page-scroll-test
        with:
          urls: |
            https://github.com/partners/service-channel-partners
            https://support.github.com/request/landing
            https://primer.style/product/getting-started/foundations/layout/
            https://support.github.com/product-guides
            https://primer.style/product/ui-patterns/degraded-experiences
            https://reg.githubuniverse.com/flow/github/universe25/attendee-portal/page/sessioncatalog
            https://primer.style/product/hooks/useResponsiveValue
          repository: lindseywild/accessibility-scanner
          token: ${{ secrets.GH_TOKEN }}
          cache_key: cached_results-lindseywild-scanner-main.json
          skip_copilot_assignment: true
